Add duckdb setup script
OvertureMaps/data pull request #94
Opened 2023-11-17 20:07 UTC by jwass

Adds a simple script that sets up duckdb views for:
* Overture planet
* admins
* base
* buildings
* places
* transportation

This should make it a bit easier for duckdb users that don't have to type the long read_parquet('s3://....') lines

2023-11-17 20:08 UTC, jwass commented
For the MS folks - @ibnt1 @varapmsft, should we make one also for Azure? and have a `setup_aws_2023_11_14.sql` and `setup_azure_2023_11_14.sql`.

2023-11-17 21:36 UTC, ibnt1 commented
> For the MS folks - @ibnt1 @varapmsft, should we make one also for Azure? and have a `setup_aws_2023_11_14.sql` and `setup_azure_2023_11_14.sql`.

that would be convenient for users, sure, but i don't think it's needed necessarily, the readme page describes already how to read from azure as well. i'm just concerned we're adding more places to update for ourselves when we release new themes for example. 
but we could generate (update) these queries programmatically with each release to mitigate that probably, with inputs being releaseVersion (to update all paths) and themesList (to create full list of all views) for example.

2023-12-14 14:49 UTC, Youssef-Harby requested changes
typo error of httpfs extension in `duckdb_queries/setup_v2023_11_14.sql`.

2023-12-14 14:49 UTC, Youssef-Harby commented on duckdb_queries/setup_v2023_11_14.sql
> +INSTALL httpsfs;
It should be `INSTALL httpfs` instead of httpsfs

2024-02-15 19:35 UTC, closed without merging